name: EquicordApp

options:
  bundleIdPrefix: com.kingtweak69
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"

targets:
  EquicordApp:
    type: application
    platform: iOS
    deploymentTarget: "18.0"

    sources:
      - path: EquicordApp
        excludes:
          - Info.plist
          - equicord.user.js

    resources:
      - path: EquicordApp/equicord.user.js

    info:
      path: EquicordApp/Info.plist
      properties:
        CFBundleDisplayName: Equicord
        CFBundleName: EquicordApp
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "3"
        UILaunchScreen: {}
        NSMicrophoneUsageDescription: Microphone access for Discord voice channels.
        NSCameraUsageDescription: Camera access for video calls.
        UIBackgroundModes:
          - audio

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kingtweak69.EquicordApp
        PRODUCT_NAME: EquicordApp
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
